### ISSUE TITLE
Command line arguments parsing

### ISSUE THREAD

**Issue by pyperanger** [pyperanger/fuptcha#4]

**Comment by pyperanger** [comment]
-f -> image path
-s -> text string
-l -> level search [ default 1 ]
-v -> verbose [ just 1 mode ]
-t -> thread [ default 1 ]
-r -> rank [ default 100% match langs ]
-h -> help blabla..

**Comment by growlnx** [comment]
For more effective error handling, we can use strtol instead of the atoi function.

**Comment by pyperanger** [comment]
reopen if any kind of argument or new feature.
